[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
headless = true
serverAddress = "0.0.0.0"
serverPort = 8501
serverMaxUploadSize = 200
serverRunOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
